# Generated by Django 6.0.2 on 2026-03-03 11:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCin', models.CharField(max_length=12, unique=True)),
                ('dateCin', models.DateField()),
                ('lieuCin', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EtatCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModeFinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Postes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('grade', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('grade', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sexes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeContrats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeContrat', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='CoordonneesBancaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rib', models.CharField(max_length=100)),
                ('photoRib', models.ImageField(blank=True, null=True, upload_to='ribs/')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordonneesBancaires', to='api.agences')),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordonneesBancaires', to='api.banques')),
            ],
        ),
        migrations.CreateModel(
            name='Personnelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=200)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('photoResidence', models.ImageField(blank=True, null=True, upload_to='residences/')),
                ('telPerso', models.CharField(blank=True, max_length=50, null=True)),
                ('emailPerso', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('cinphoto', models.FileField(upload_to='photocin/')),
                ('acteNaissance', models.FileField(upload_to='acteNaissance/')),
                ('casierjudiciaire', models.FileField(upload_to='Casierjudiciaire/')),
                ('cin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnelles', to='api.cins')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDuPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('société', models.CharField(max_length=100)),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('description', models.TextField()),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HistoriqueDuPoste', to='api.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('organisme', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('attestation', models.FileField(upload_to='attestation/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Formation', to='api.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPere', models.CharField(blank=True, max_length=100, null=True)),
                ('prenomPere', models.CharField(blank=True, max_length=100, null=True)),
                ('nomMere', models.CharField(blank=True, max_length=100, null=True)),
                ('prenomMere', models.CharField(blank=True, max_length=100, null=True)),
                ('nomConjoint', models.CharField(blank=True, max_length=100, null=True)),
                ('prenomConjoint', models.CharField(blank=True, max_length=100, null=True)),
                ('nombreEnfant', models.CharField(blank=True, max_length=100, null=True)),
                ('acteMariage', models.FileField(upload_to='acteMariage/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Famille', to='api.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreExperience', models.IntegerField()),
                ('entreprise', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('description', models.TextField()),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Experience', to='api.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=200)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('certificatVie', models.FileField(upload_to='certificatVie/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Enfant', to='api.personnelles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etablissement', models.CharField(max_length=100)),
                ('dateObtention', models.DateField()),
                ('photo', models.FileField(upload_to='photos/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Diplome', to='api.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('data', models.ImageField(upload_to='photos/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='api.personnelles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Propos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(blank=True, max_length=50, null=True)),
                ('stat', models.CharField(blank=True, max_length=50, null=True)),
                ('numeroCnaps', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('nombreEnfant', models.IntegerField(blank=True, null=True)),
                ('etatCivil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propos', to='api.etatcivil')),
            ],
        ),
        migrations.AddField(
            model_name='personnelles',
            name='propos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnelles', to='api.propos'),
        ),
        migrations.CreateModel(
            name='ContactUrgences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactUrgence', to='api.personnelles')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactUrgent', to='api.relations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='api.propos', to_field='email')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='Fonctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('financement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financement', to='api.modefinancement')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fonctions', to='api.personnelles')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fonctions', to='api.postes')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fonctions', to='api.services')),
            ],
        ),
        migrations.AddField(
            model_name='personnelles',
            name='sexe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnelles', to='api.sexes'),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroContrat', models.CharField()),
                ('photoContrat', models.FileField(upload_to='Contrats/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrat', to='api.personnelles')),
                ('typeContrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='typecontrats', to='api.typecontrats')),
            ],
        ),
    ]
