# Generated by Django 6.0.3 on 2026-06-05 12:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('rib', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Planification Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Planification',
                'db_table': 'config_planning',
            },
        ),
        migrations.CreateModel(
            name='DiplomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Type de diplôme',
                'verbose_name_plural': 'Types de diplômes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EtatCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeFinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personnelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(max_length=200)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('quartier', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('photoResidence', models.ImageField(blank=True, null=True, upload_to='residences/')),
                ('telPerso', models.CharField(blank=True, max_length=50, null=True)),
                ('emailPerso', models.EmailField(blank=True, max_length=100, null=True)),
                ('cinphoto', models.FileField(upload_to='photocin/')),
                ('acteNaissance', models.FileField(upload_to='acteNaissance/')),
                ('casierjudiciaire', models.FileField(upload_to='Casierjudiciaire/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sexes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('duree_max', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congé',
            },
        ),
        migrations.CreateModel(
            name='TypeContrats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeContrat', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.PositiveIntegerField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etape_validation', models.CharField(blank=True, choices=[('chef', 'En attente chef'), ('gp_rf', 'En attente GP/RF'), ('cn', 'En attente CN'), ('rh', 'En attente RH'), ('termine', 'Terminé')], default='chef', max_length=20, null=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fonctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('is_chef', models.BooleanField(default=False)),
                ('chef_direct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonnes', to='api.fonctions')),
                ('financement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financement', to='api.modefinancement')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonctions', to='api.postes')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonctions', to='api.services')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('validation_requise', '🔔 Validation requise'), ('remplacement_requis', '🔄 Validation par remplacement'), ('conge_approuve', '✅ Congé approuvé'), ('conge_refuse', '❌ Congé refusé'), ('conge_en_cours', '⏳ Congé en cours de validation'), ('rappel_validation', '⏰ Rappel de validation'), ('conge_annule', '🚫 Congé annulé')], max_length=40)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.conge')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.login')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PassationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('date_reprise', models.DateField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passations_services', to='api.fonctions')),
                ('remplacant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passations_en_tant_que_remplacant', to='api.personnelles')),
                ('titulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passations_en_tant_que_titulaire', to='api.personnelles')),
                ('statut', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passations_services_statut', to='api.statut')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conge',
            name='passation_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_passation', to='api.passationservice'),
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('motif', models.TextField()),
                ('duree', models.FloatField(default=0)),
                ('solde_initial', models.FloatField(default=0)),
                ('solde_restant', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.personnelles')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='login',
            name='personnelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login', to='api.personnelles'),
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('organisme', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('annee', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('attestation', models.FileField(upload_to='attestation/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Formation', to='api.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPere', models.CharField(blank=True, max_length=255, null=True)),
                ('nomMere', models.CharField(blank=True, max_length=255, null=True)),
                ('nomConjoint', models.CharField(blank=True, max_length=100, null=True)),
                ('prenomConjoint', models.CharField(blank=True, max_length=100, null=True)),
                ('telConjoint', models.CharField(blank=True, max_length=100, null=True)),
                ('adresseConjoint', models.CharField(max_length=100)),
                ('emailConjoint', models.EmailField(blank=True, max_length=100, null=True)),
                ('nombreEnfant', models.CharField(blank=True, max_length=100, null=True)),
                ('acteMariage', models.FileField(upload_to='acteMariage/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Famille', to='api.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Experience', to='api.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(blank=True, max_length=150, null=True, verbose_name='Filière')),
                ('lieu', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lieu')),
                ('etablissement', models.CharField(max_length=100)),
                ('anneeObtention', models.PositiveIntegerField(blank=True, null=True, verbose_name="Année d'obtention")),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('type_diplome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diplomes', to='api.diplometype', verbose_name='Type de diplôme')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='api.personnelles')),
            ],
            options={
                'verbose_name': 'Diplôme',
                'verbose_name_plural': 'Diplômes',
                'ordering': ['-anneeObtention'],
            },
        ),
        migrations.CreateModel(
            name='CoordonneesBancaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rib', models.CharField(max_length=100)),
                ('photoRib', models.ImageField(blank=True, null=True, upload_to='ribs/')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordonneesBancaires', to='api.agences')),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordonneesBancaires', to='api.banques')),
                ('personnelle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordonnees_bancaires', to='api.personnelles')),
            ],
        ),
        migrations.AddField(
            model_name='conge',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='api.personnelles'),
        ),
        migrations.CreateModel(
            name='Cins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCin', models.CharField(max_length=12, unique=True)),
                ('dateCin', models.DateField()),
                ('lieuCin', models.CharField(max_length=100)),
                ('numeroDuplicata', models.CharField(blank=True, max_length=50, null=True)),
                ('dateDuplicata', models.DateField(blank=True, null=True)),
                ('lieuDuplicata', models.CharField(blank=True, max_length=100, null=True)),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cins', to='api.personnelles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.ImageField(upload_to='photos/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.personnelles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Propos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(blank=True, max_length=50, null=True)),
                ('stat', models.CharField(blank=True, max_length=50, null=True)),
                ('numeroCnaps', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('nombreEnfant', models.IntegerField(blank=True, null=True)),
                ('etatCivil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propos', to='api.etatcivil')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propos_list', to='api.personnelles')),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='api.propos', to_field='email'),
        ),
        migrations.CreateModel(
            name='ContactUrgences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactUrgence', to='api.personnelles')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactUrgent', to='api.relations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loginadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_login', to='api.role')),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='api.role'),
        ),
        migrations.AddField(
            model_name='personnelles',
            name='sexe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnelles', to='api.sexes'),
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(max_length=200)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('certificatVie', models.FileField(upload_to='certificatVie/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enfant', to='api.personnelles')),
                ('sexe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enfant', to='api.sexes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('utilise', models.PositiveIntegerField(default=0)),
                ('reste', models.PositiveIntegerField(default=0)),
                ('is_manual', models.BooleanField(default=False)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conge', to='api.personnelles')),
            ],
        ),
        migrations.AddField(
            model_name='conge',
            name='solde_conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges_utilises', to='api.soldeconge'),
        ),
        migrations.AddField(
            model_name='conge',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='api.statut'),
        ),
        migrations.CreateModel(
            name='CongePlanifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges_planifies', to='api.personnelles')),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges_planifies', to='api.typeconge')),
            ],
            options={
                'db_table': 'api_conges_planifies',
                'ordering': ['date_debut'],
            },
        ),
        migrations.AddField(
            model_name='conge',
            name='type_conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='api.typeconge'),
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroContrat', models.CharField(max_length=100, unique=True)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('periodeEssai', models.CharField(blank=True, max_length=100, null=True)),
                ('dateFinEssai', models.DateField(blank=True, null=True)),
                ('photoContrat', models.FileField(blank=True, null=True, upload_to='Contrats/')),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_actif', models.BooleanField(default=True, verbose_name='Contrat Actif')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='api.fonctions')),
                ('financement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='api.modefinancement')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='api.personnelles')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.services')),
                ('typeContrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='api.typecontrats')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-dateDebut'],
            },
        ),
        migrations.CreateModel(
            name='ValidationConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('chef', 'Chef direct'), ('gp', 'GP'), ('rf', 'RF'), ('cn', 'CN'), ('rh', 'RH')], max_length=20)),
                ('decision', models.CharField(choices=[('approuve', 'Approuvé'), ('refuse', 'Refusé')], max_length=10)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='api.conge')),
                ('valideur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_effectuees', to='api.login')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='personnelles',
            constraint=models.UniqueConstraint(condition=models.Q(('emailPerso__isnull', False)), fields=('emailPerso',), name='unique_emailPerso_not_null'),
        ),
        migrations.AlterUniqueTogether(
            name='soldeconge',
            unique_together={('personnel', 'annee')},
        ),
    ]
