# Generated by Django 6.0.2 on 2026-02-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPere', models.CharField(blank=True, max_length=100, null=True)),
                ('PrenomPere', models.CharField(blank=True, max_length=100, null=True)),
                ('nomMere', models.CharField(blank=True, max_length=100, null=True)),
                ('PrenomMere', models.CharField(blank=True, max_length=100, null=True)),
                ('nomConjoint', models.CharField(blank=True, max_length=100, null=True)),
                ('PrenomConjoint', models.CharField(blank=True, max_length=100, null=True)),
                ('nombreEnfant', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
