# Generated by Django 6.0.3 on 2026-03-12 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordonneesbancaires',
            name='personnelle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordonnees_bancaires', to='api.personnelles'),
        ),
    ]
