# Generated by Django 6.0.3 on 2026-04-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conge',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='soldeconge',
            options={},
        ),
    ]
