# Generated by Django 6.0.5 on 2026-05-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonctions',
            name='is_chef',
            field=models.BooleanField(default=False),
        ),
    ]
