# Generated by Django 6.0.2 on 2026-02-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonneesbancaires',
            name='rib',
            field=models.CharField(max_length=100),
        ),
    ]
