# Generated by Django 6.0.3 on 2026-04-07 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='personnelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login', to='api.personnelles'),
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='Approuvé', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.personnelles')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
    ]
