# Generated by Django 6.0.3 on 2026-03-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrat',
            old_name='dateEssai',
            new_name='dateFinEssai',
        ),
        migrations.RenameField(
            model_name='contrat',
            old_name='essai',
            new_name='periodeEssai',
        ),
        migrations.AlterField(
            model_name='famille',
            name='emailConjoint',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fonctions',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonctions', to='api.postes'),
        ),
    ]
