# Generated by Django 6.0.3 on 2026-05-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='etape_validation',
            field=models.CharField(blank=True, choices=[('chef', 'En attente chef'), ('gp_rf', 'En attente GP/RF'), ('cn', 'En attente CN'), ('rh', 'En attente RH'), ('termine', 'Terminé')], default='chef', max_length=20, null=True),
        ),
    ]
