# Generated by Django 6.0.5 on 2026-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
