# Generated by Django 6.0.3 on 2026-06-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelles',
            name='emailPerso',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='personnelles',
            constraint=models.UniqueConstraint(condition=models.Q(('emailPerso__isnull', False)), fields=('emailPerso',), name='unique_emailPerso_not_null'),
        ),
    ]
