# Generated by Django 6.0.3 on 2026-04-15 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('duree_max', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congé',
            },
        ),
        migrations.CreateModel(
            name='Loginadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logins', to='api.role')),
            ],
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('utilise', models.PositiveIntegerField(default=0)),
                ('reste', models.PositiveIntegerField(default=0)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conge', to='api.personnelles')),
            ],
            options={
                'verbose_name': 'Solde de congé',
                'verbose_name_plural': 'Soldes de congé',
                'unique_together': {('personnel', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.PositiveIntegerField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='api.personnelles')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_validated', to=settings.AUTH_USER_MODEL)),
                ('solde_conge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges_utilises', to='api.soldeconge')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='api.statut')),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='api.typeconge')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-created_at'],
            },
        ),
    ]
