# Generated by Django 6.0.2 on 2026-02-27 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='datedebut',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='datefin',
        ),
        migrations.AddField(
            model_name='enfant',
            name='acteNaissance',
            field=models.FileField(default=1, upload_to='acteNaissance/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfant',
            name='certificatVie',
            field=models.FileField(default=1, upload_to='certificatVie/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famille',
            name='acteMariage',
            field=models.FileField(default=2, upload_to='acteMariage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='annee',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formation',
            name='lieu',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelles',
            name='casierjudiciaire',
            field=models.FileField(default=1, upload_to='Casierjudiciaire/'),
            preserve_default=False,
        ),
    ]
