# Generated by Django 5.2.10 on 2026-02-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nifStat', models.CharField(blank=True, max_length=50, null=True)),
                ('numeroCnaps', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('nombreEnfant', models.IntegerField(blank=True, null=True)),
                ('etatCivil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propos', to='api.etatcivil')),
            ],
        ),
    ]
