# Generated by Django 6.0.2 on 2026-02-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatcivil',
            name='tel',
            field=models.CharField(default=3, max_length=15),
            preserve_default=False,
        ),
    ]
