# Generated by Django 6.0.3 on 2026-03-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_famille_emailconjoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrat',
            old_name='dateEssai',
            new_name='dateFinEssai',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='essai',
        ),
        migrations.AddField(
            model_name='contrat',
            name='periodeEssai',
            field=models.CharField(null=True),
        ),
    ]
