# Generated by Django 6.0.3 on 2026-04-10 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_loginadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginadmin',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logins', to='api.role'),
        ),
    ]
