# Generated by Django 6.0.2 on 2026-02-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cins_numerocin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cins',
            name='numeroCin',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
