# Generated by Django 6.0.2 on 2026-02-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_famille'),
    ]

    operations = [
        migrations.RenameField(
            model_name='famille',
            old_name='PrenomConjoint',
            new_name='prenomConjoint',
        ),
        migrations.RenameField(
            model_name='famille',
            old_name='PrenomMere',
            new_name='prenomMere',
        ),
        migrations.RenameField(
            model_name='famille',
            old_name='PrenomPere',
            new_name='prenomPere',
        ),
    ]
