# Generated by Django 6.0.3 on 2026-03-12 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coordonneesbancaires_personnelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacturgences',
            name='personnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactUrgence', to='api.personnelles'),
        ),
        migrations.AlterField(
            model_name='contacturgences',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactUrgent', to='api.relations'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='personnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='api.personnelles'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='typeContrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typecontrats', to='api.typecontrats'),
        ),
        migrations.AlterField(
            model_name='coordonneesbancaires',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordonneesBancaires', to='api.agences'),
        ),
        migrations.AlterField(
            model_name='coordonneesbancaires',
            name='banque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordonneesBancaires', to='api.banques'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='personnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Diplome', to='api.personnelles'),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='personnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enfant', to='api.personnelles'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='personnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Experience', to='api.personnelles'),
        ),
        migrations.AlterField(
            model_name='famille',
            name='personnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Famille', to='api.personnelles'),
        ),
        migrations.AlterField(
            model_name='fonctions',
            name='financement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financement', to='api.modefinancement'),
        ),
        migrations.AlterField(
            model_name='fonctions',
            name='personnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonctions', to='api.personnelles'),
        ),
        migrations.AlterField(
            model_name='fonctions',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonctions', to='api.postes'),
        ),
        migrations.AlterField(
            model_name='fonctions',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonctions', to='api.services'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='personnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Formation', to='api.personnelles'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='personnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.personnelles'),
        ),
        migrations.AlterField(
            model_name='propos',
            name='etatCivil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propos', to='api.etatcivil'),
        ),
    ]
