# Generated by Django 6.0.5 on 2026-05-22 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fonctions_is_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonctions',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonctions', to='api.services'),
        ),
    ]
