# Generated by Django 6.0.2 on 2026-02-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_formation_datedebut_remove_formation_datefin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContrats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeContrat', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroContrat', models.CharField()),
                ('photoContrat', models.FileField(upload_to='Contrats/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrat', to='api.personnelles')),
                ('typeContrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='typecontrats', to='api.typecontrats')),
            ],
        ),
    ]
