# Generated by Django 6.0.3 on 2026-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_conge_options_alter_soldeconge_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldeconge',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
