# Generated by Django 6.0.3 on 2026-06-09 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_conge_etape_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_validated', to='api.login'),
        ),
    ]
