# Generated by Django 6.0.5 on 2026-05-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conge_etape_validation'),
        ('api', '0002_personnelles_is_active'),
    ]

    operations = [
    ]
