# Generated by Django 6.0.2 on 2026-02-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_coordonneesbancaires_rib'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonctions',
            name='nom',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
