# Generated by Django 6.0.3 on 2026-06-08 12:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_conge_etape_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContrat',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('NumeroContrat', models.CharField(db_index=True, max_length=100)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('periodeEssai', models.CharField(blank=True, max_length=100, null=True)),
                ('dateFinEssai', models.DateField(blank=True, null=True)),
                ('photoContrat', models.TextField(blank=True, max_length=100, null=True)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_actif', models.BooleanField(default=True, verbose_name='Contrat Actif')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('financement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.modefinancement')),
                ('fonction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.fonctions')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personnelle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.personnelles')),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.services')),
                ('typeContrat', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.typecontrats')),
            ],
            options={
                'verbose_name': 'historical Contrat',
                'verbose_name_plural': 'historical Contrats',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
