# Generated by Django 6.0.3 on 2026-04-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='statut',
            field=models.CharField(choices=[('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='Approuvé', max_length=20),
        ),
    ]
