# Generated by Django 6.0.2 on 2026-02-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_etatcivil_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatcivil',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='etatcivil',
            name='tel',
        ),
    ]
