# Generated by Django 6.0.3 on 2026-05-18 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fonctions_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CongePlanifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.PositiveIntegerField(blank=True, editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges_planifies', to='api.personnelles')),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges_planifies', to='api.typeconge')),
            ],
            options={
                'db_table': 'api_conges_planifies',
                'ordering': ['date_debut'],
            },
        ),
    ]
