# Generated by Django 6.0.3 on 2026-06-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_conge_validated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='etape_validation',
            field=models.CharField(blank=True, choices=[('passation', 'En attente remplaçant'), ('chef', 'En attente chef'), ('gp_pf', 'En attente GP/PF'), ('cn', 'En attente CN'), ('rh', 'En attente RH'), ('termine', 'Terminé')], default='passation', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('validation_requise', ' Validation requise'), ('remplacement_requis', ' Validation par remplacement'), ('conge_approuve', 'Congé approuvé'), ('conge_refuse', ' Congé refusé'), ('conge_en_cours', 'Congé en cours de validation'), ('rappel_validation', ' Rappel de validation'), ('conge_annule', ' Congé annulé'), ('rappel_conge', 'Rappel prise de congé')], max_length=40),
        ),
    ]
