# Generated by Django 6.0.3 on 2026-03-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contacturgences_personnelle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelles',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='personnelles',
            name='propos',
        ),
        migrations.AddField(
            model_name='cins',
            name='personnelle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cin', to='api.personnelles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propos',
            name='personnelle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='propos', to='api.personnelles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propos',
            name='etatCivil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etatcivil', to='api.etatcivil'),
        ),
    ]
