# Generated by Django 6.0.2 on 2026-02-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_prenomconjoint_famille_prenomconjoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='personnelle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Famille', to='api.personnelles'),
            preserve_default=False,
        ),
    ]
