# Generated by Django 6.0.3 on 2026-06-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historicalcontrat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalContrat',
        ),
    ]
