# Generated by Django 6.0.5 on 2026-05-22 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fonctions_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('niveau', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Type de diplôme',
                'verbose_name_plural': 'Types de diplômes',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='diplome',
            options={'ordering': ['-dateObtention'], 'verbose_name': 'Diplôme', 'verbose_name_plural': 'Diplômes'},
        ),
        migrations.RemoveField(
            model_name='diplome',
            name='nom',
        ),
        migrations.AddField(
            model_name='diplome',
            name='filiere',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='personnelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='api.personnelles'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='diplome',
            name='type_diplome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomes', to='api.diplometype', verbose_name='Type de diplôme'),
        ),
    ]
