# Generated by Django 6.0.2 on 2026-03-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_typecontrats_contrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfant',
            name='acteNaissance',
        ),
        migrations.AddField(
            model_name='personnelles',
            name='acteNaissance',
            field=models.FileField(default=1, upload_to='acteNaissance/'),
            preserve_default=False,
        ),
    ]
