# Generated by Django 6.0.3 on 2026-04-27 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_soldeconge_is_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('date_reprise', models.DateField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passations_services', to='api.fonctions')),
                ('remplacant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passations_en_tant_que_remplacant', to='api.personnelles')),
                ('titulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passations_en_tant_que_titulaire', to='api.personnelles')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
