# Generated by Django 6.0.2 on 2026-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_etatcivil_prenom_remove_etatcivil_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
