# Generated by Django 6.0.3 on 2026-04-14 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_loginadmin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('total', models.IntegerField()),
                ('reste', models.IntegerField()),
                ('Personnelles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes', to='api.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
                ('nombreJours', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='api.personnelles')),
                ('soldeConge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solde_conge', to='api.soldeconge')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statut_conge', to='api.statut')),
                ('typeConge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_conge', to='api.typeconge')),
            ],
        ),
    ]
