# Generated by Django 6.0.3 on 2026-03-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_dateessai_contrat_datefinessai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonctions',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonctions', to='api.postes'),
        ),
    ]
