# Generated by Django 6.0.3 on 2026-06-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_conge_validated_by'),
        ('api', '0004_delete_historicalcontrat'),
    ]

    operations = [
    ]
