# Generated by Django 6.0.3 on 2026-03-25 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_fonctions_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famille',
            name='prenomMere',
        ),
        migrations.RemoveField(
            model_name='famille',
            name='prenomPere',
        ),
        migrations.AddField(
            model_name='cins',
            name='dateDuplicata',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cins',
            name='lieuDuplicata',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cins',
            name='numeroduplicata',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='salaire',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enfant',
            name='sexe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enfant', to='api.sexes'),
            preserve_default=False,
        ),
    ]
