# Generated by Django 6.0.3 on 2026-03-12 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_personnelles_cin_remove_personnelles_propos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cins',
            name='personnelle',
        ),
        migrations.RemoveField(
            model_name='propos',
            name='personnelle',
        ),
        migrations.AlterField(
            model_name='propos',
            name='etatCivil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propos', to='api.etatcivil'),
        ),
    ]
