# Generated by Django 6.0.5 on 2026-05-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_diplometype_alter_diplome_options_remove_diplome_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplometype',
            name='niveau',
        ),
        migrations.AddField(
            model_name='diplome',
            name='lieu',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lieu'),
        ),
    ]
