# Generated by Django 6.0.3 on 2026-04-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_statut_typeconge_soldeconge_conge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='date_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='date_fin',
            field=models.DateTimeField(),
        ),
    ]
