# Generated by Django 6.0.3 on 2026-05-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_congeplanifie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Planification Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Planification',
                'db_table': 'config_planning',
            },
        ),
    ]
