# Generated by Django 6.0.2 on 2026-03-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_enfant_actenaissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='photo',
            field=models.FileField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='attestation',
            field=models.FileField(upload_to='attestation/'),
        ),
    ]
