# Generated by Django 6.0.3 on 2026-04-27 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_passationservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='passation_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_passation', to='api.passationservice'),
        ),
    ]
