# Generated by Django 6.0.2 on 2026-02-19 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_famille_personnelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('etablissement', models.CharField(max_length=100)),
                ('dateObtention', models.DateField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Diplome', to='api.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=200)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=200)),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Enfant', to='api.personnelles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('description', models.TextField()),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Experience', to='api.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('organisme', models.CharField(max_length=100)),
                ('datedebut', models.DateTimeField()),
                ('datefin', models.DateTimeField()),
                ('attestation', models.ImageField(upload_to='photos/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Formation', to='api.personnelles')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueDuPoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('société', models.CharField(max_length=100)),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('description', models.TextField()),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HistoriqueDuPoste', to='api.personnelles')),
            ],
        ),
    ]
