# Generated by Django 6.0.5 on 2026-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_diplometype_niveau_diplome_lieu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diplome',
            options={'ordering': ['-anneeObtention'], 'verbose_name': 'Diplôme', 'verbose_name_plural': 'Diplômes'},
        ),
        migrations.RemoveField(
            model_name='diplome',
            name='dateObtention',
        ),
        migrations.AddField(
            model_name='diplome',
            name='anneeObtention',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Année d'obtention"),
        ),
    ]
