# Generated by Django 6.0.3 on 2026-04-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_permissions_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name': 'Permission'},
        ),
        migrations.AddField(
            model_name='permissions',
            name='duree',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='permissions',
            name='solde_initial',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='permissions',
            name='solde_restant',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='En attente', max_length=20),
        ),
    ]
