# Generated by Django 6.0.2 on 2026-02-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_diplome_enfant_experience_formation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='datedebut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='formation',
            name='datefin',
            field=models.DateField(),
        ),
    ]
