# Generated by Django 6.0.3 on 2026-03-12 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_cins_personnelle_remove_propos_personnelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cins',
            name='personnelle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cins', to='api.personnelles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propos',
            name='personnelle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='propos', to='api.personnelles'),
            preserve_default=False,
        ),
    ]
