# Generated by Django 6.0.2 on 2026-03-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_diplome_photo_alter_formation_attestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelles',
            name='cinphoto',
            field=models.FileField(default=1, upload_to='photocin/'),
            preserve_default=False,
        ),
    ]
