# Generated by Django 6.0.3 on 2026-06-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_conge_etape_validation_and_more'),
        ('api', '0005_merge_20260609_1330'),
    ]

    operations = [
    ]
