# Generated by Django 6.0.3 on 2026-05-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_configplanning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congeplanifie',
            name='nombre_jours',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
