# Generated by Django 6.0.3 on 2026-04-29 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conge_passation_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='passationservice',
            name='statut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='passations_services_statut', to='api.statut'),
            preserve_default=False,
        ),
    ]
