# Generated by Django 6.0.3 on 2026-03-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_famille_prenommere_remove_famille_prenompere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='nomMere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='famille',
            name='nomPere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
