# Generated by Django 6.0.3 on 2026-03-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cins_personnelle_propos_personnelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='postes',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
