# Generated by Django 6.0.3 on 2026-05-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personnelles_is_active'),
        ('api', '0006_alter_congeplanifie_nombre_jours'),
        ('api', '0006_alter_diplome_options_remove_diplome_dateobtention_and_more'),
    ]

    operations = [
    ]
