# Generated by Django 6.0.2 on 2026-02-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_formation_datedebut_alter_formation_datefin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cins',
            name='numeroCin',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='attestation',
            field=models.ImageField(upload_to='attestation/'),
        ),
    ]
