# Generated by Django 6.0.3 on 2026-03-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_famille_nommere_alter_famille_nompere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cins',
            old_name='numeroduplicata',
            new_name='numeroDuplicata',
        ),
    ]
