# Generated by Django 6.0.5 on 2026-05-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_diplome_options_remove_diplome_dateobtention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonctions',
            name='chef_direct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonnes', to='api.fonctions'),
        ),
    ]
