# Generated by Django 6.0.3 on 2026-04-29 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_passationservice_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passationservice',
            name='statut',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passations_services_statut', to='api.statut'),
        ),
    ]
