# Generated by Django 6.0.3 on 2026-04-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_permissions_options_permissions_duree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='solde_initial',
        ),
        migrations.AddField(
            model_name='permissions',
            name='solde_jours',
            field=models.FloatField(default=40.0),
        ),
    ]
