# Generated by Django 6.0.3 on 2026-06-22 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20260622_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('duree_defaut', models.FloatField(blank=True, help_text='Null = durée à discrétion RH', null=True)),
                ('est_fractionnable', models.BooleanField(default=False)),
                ('delai_prise', models.PositiveSmallIntegerField(blank=True, help_text='Délai max en jours (ex: 15 pour naissance)', null=True)),
            ],
            options={
                'verbose_name': 'Événement de permission',
                'verbose_name_plural': 'Événements de permission',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='fonctions',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonctions', to='api.services'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='motif',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='evenement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='api.evenementpermission'),
        ),
        migrations.CreateModel(
            name='SoldePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField()),
                ('solde_disponible', models.FloatField(default=10.0)),
                ('date_reinitialisation', models.DateTimeField(blank=True, null=True)),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_permission', to='api.personnelles')),
            ],
            options={
                'verbose_name': 'Solde de permission',
                'verbose_name_plural': 'Soldes de permission',
                'ordering': ['-annee'],
                'unique_together': {('personnelle', 'annee')},
            },
        ),
    ]
