# Generated by Django 6.0.3 on 2026-03-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_postes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacturgences',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacturgences',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
