# Generated by Django 6.0.3 on 2026-05-28 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20260528_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplome',
            name='type_diplome',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='diplomes', to='api.diplometype', verbose_name='Type de diplôme'),
            preserve_default=False,
        ),
    ]
