# Generated by Django 6.0.3 on 2026-03-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_numeroduplicata_cins_numeroduplicata'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelles',
            name='quartier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personnelles',
            name='ville',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
