# Generated by Django 6.0.3 on 2026-04-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_passationservice_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passationservice',
            name='fonction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
