# Generated by Django 6.0.2 on 2026-03-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_modefinancement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fonctions',
            name='financement',
        ),
        migrations.AddField(
            model_name='fonctions',
            name='modeFinancement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modefiancement', to='api.modefinancement'),
        ),
    ]
