# Generated by Django 6.0.2 on 2026-02-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cins_numerocin_alter_formation_attestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordonneesbancaires',
            name='photoRib',
            field=models.ImageField(blank=True, null=True, upload_to='ribs/'),
        ),
        migrations.AddField(
            model_name='personnelles',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personnelles',
            name='photoResidence',
            field=models.ImageField(blank=True, null=True, upload_to='residences/'),
        ),
    ]
