# Generated by Django 6.0.3 on 2026-04-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_permissions_solde_initial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='solde_jours',
        ),
        migrations.AddField(
            model_name='permissions',
            name='solde_initial',
            field=models.FloatField(default=0),
        ),
    ]
