# Generated by Django 6.0.3 on 2026-04-30 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_passationservice_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passationservice',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passations_services', to='api.fonctions'),
        ),
    ]
