# Generated by Django 6.0.3 on 2026-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_contacturgences_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='essai',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famille',
            name='adresseConjoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='famille',
            name='emailConjoint',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='famille',
            name='telConjoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postes',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agences',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banques',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacturgences',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='NumeroContrat',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etatcivil',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modefinancement',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personnelles',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postes',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relations',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sexes',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
