# Generated by Django 6.0.2 on 2026-02-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCin', models.PositiveIntegerField(max_length=50, unique=True)),
                ('dateCin', models.DateField()),
                ('lieuCin', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
