# Generated by Django 6.0.3 on 2026-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_diplome_type_diplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='is_actif',
            field=models.BooleanField(default=True, verbose_name='Contrat Actif'),
        ),
    ]
