# Generated by Django 6.0.2 on 2026-02-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_coordonneesbancaires_photorib_personnelles_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonctions',
            name='financement',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
