# Generated by Django 6.0.3 on 2026-06-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # On le branche directement sur le 0007 que vous venez de me montrer
        ('api', '0006_merge_20260622_0728'), 
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='is_actif',
            field=models.BooleanField(default=True, verbose_name='Contrat Actif'),
        ),
    ]