# Generated by Django 6.0.3 on 2026-05-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_passationservice_fonction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conge',
            name='passation_service',
        ),
    ]
