# Generated by Django 6.0.2 on 2026-02-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fonctions_financement'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelles',
            name='emailPerso',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnelles',
            name='telPerso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
