# Generated by Django 6.0.2 on 2026-02-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
        migrations.RenameModel(
            old_name='Sexe',
            new_name='Sexes',
        ),
        migrations.DeleteModel(
            name='Poste',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
