# Generated by Django 6.0.2 on 2026-02-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_propos'),
        ('api', '0010_postes_relations_rename_service_services_and_more'),
    ]

    operations = [
    ]
