# Generated by Django 6.0.2 on 2026-02-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_personnelles_emailperso_personnelles_telperso'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='nombreExperience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
