# Generated by Django 6.0.2 on 2026-02-05 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20260205_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cins',
            name='numeroCin',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Personnelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=100)),
                ('sexe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnelles', to='api.sexes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
