# Generated by Django 6.0.3 on 2026-05-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_conge_passation_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonctions',
            name='superieurs',
            field=models.ManyToManyField(blank=True, related_name='subordonnes', to='api.login'),
        ),
    ]
