# Generated by Django 6.0.2 on 2026-02-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_experience_nombreexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='agences',
            name='ville',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
