# Generated by Django 6.0.3 on 2026-05-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_conge_options_alter_soldeconge_options'),
        ('api', '0008_alter_diplome_type_diplome'),
        ('api', '0011_conge_passation_service'),
    ]

    operations = [
    ]
