# Generated by Django 6.0.3 on 2026-05-07 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fonctions_superieurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('chef', 'Chef direct'), ('gp', 'GP'), ('rf', 'RF'), ('cn', 'CN'), ('rh', 'RH')], max_length=20)),
                ('decision', models.CharField(choices=[('approuve', 'Approuvé'), ('refuse', 'Refusé')], max_length=10)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='api.conge')),
                ('valideur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_effectuees', to='api.login')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
