# Generated by Django 6.0.2 on 2026-02-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_cins_numerocin_personnelles'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelles',
            name='cin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnelles', to='api.cins'),
        ),
        migrations.AddField(
            model_name='personnelles',
            name='propos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnelles', to='api.propos'),
        ),
        migrations.AlterField(
            model_name='personnelles',
            name='lieuNaissance',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personnelles',
            name='prenom',
            field=models.CharField(max_length=200),
        ),
    ]
