# Generated by Django 6.0.2 on 2026-02-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_personnelles_cin_personnelles_propos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUrgences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=100)),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactUrgence', to='api.personnelles')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactUrgent', to='api.relations')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
