# Generated by Django 6.0.2 on 2026-02-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contacturgences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fonctions', to='api.personnelles')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fonctions', to='api.postes')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fonctions', to='api.services')),
            ],
        ),
    ]
