# Generated by Django 6.0.2 on 2026-02-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_fonction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fonction',
            new_name='Fonctions',
        ),
    ]
