# Generated by Django 6.0.2 on 2026-02-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_banque'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banque',
            new_name='Banques',
        ),
    ]
