# Generated by Django 6.0.2 on 2026-02-06 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_agences'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordonneesBancaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rib', models.CharField(max_length=30)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordonneesBancaires', to='api.agences')),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coordonneesBancaires', to='api.banques')),
            ],
        ),
    ]
