# Generated by Django 6.0.2 on 2026-02-06 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_coordonneesbancaires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('data', models.ImageField(upload_to='photos/')),
                ('personnelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='api.personnelles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
