from .propos.etatCivils import EtatCivil
from .propos.propos import Propos
from .propos.sexe import Sexes
from .fonction.service import Services
from .fonction.poste import Postes
from .contact.relation import Relations
from .propos.Cins import Cins
from .propos.personnelles import Personnelles
from .contact.contactUrgences import ContactUrgences
from .fonction.fonctions import Fonctions
from .banque.banques import Banques
from .banque.agences import Agences
from .banque.coordonneesBancaires import CoordonneesBancaires
from .propos.photos import Photos
from .propos.famille import Famille
from .diplome.formation import Formation
from .diplome.experience import Experience
from .diplome.diplome import Diplome
from .propos.enfant import Enfant
from .fonction.contrat import Contrat
from .fonction.typeContrat import TypeContrats
from .fonction.modefinancement import ModeFinancement
from .auth.login.loginModel import Login
from .role.roleModel import Role
from .conge.conge import Conge
from .conge.soldeConge import SoldeConge
from .conge.statut import Statut
from .conge.typeConges import TypeConge
from .conge.passationservice import PassationService
from .conge.validationConge import ValidationConge
from .permission.permissionModel import Permissions
from .diplome.typeDiplome import DiplomeType
from .conge.notification import Notification