from .propos.etatCivils import EtatCivil
from .propos.propos import Propos
from .propos.sexe import Sexes
from .fonction.service import Services
from .fonction.poste import Postes
from .contact.relation import Relations
from .propos.Cins import Cins
from .propos.personnelles import Personnelles
from .contact.contactUrgences import ContactUrgences
from .fonction.fonctions import Fonctions
from .banque.banques import Banques
from .banque.agences import Agences
from .banque.coordonneesBancaires import CoordonneesBancaires
from .propos.photos import Photos
from .fonction.superieurs import Superieur
from .propos.famille import Famille
