from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from api.controllers import *
urlpatterns = [
    path('login', LoginController.as_view(), name='login'),
    path('personnelle', PersonnelleController.as_view(), name='personnelle'),
    path('etat-civils', EtatCivilController.as_view(), name='etat-civils'),
    path("etat-civils/<int:id>/", EtatCivilController.as_view(), name="etatcivil-detail"),
    path('propos', ProposController.as_view(), name='propos'),
    path("propos/<int:id>/", ProposController.as_view(), name="propos-detail"),
    path("sexes", SexeController.as_view(), name="sexes"),
    path("sexes/<int:id>/", SexeController.as_view(), name="sexe-detail"),
    path("services", ServiceController.as_view(), name="services"),
    path("services/<int:id>/", ServiceController.as_view(), name="service-detail"),
    path("postes", PosteController.as_view(), name="postes"),
    path("postes/<int:id>/", PosteController.as_view(), name="poste-detail"),
    path("relations", RelationController.as_view(), name="relations"),
    path("relations/<int:id>/", RelationController.as_view(), name="relation-detail"),
    path("cins", CinsController.as_view(), name="cins"),
    path("cins/<int:id>/", CinsController.as_view(), name="cins-detail"),
    path("personnelles", PersonnelleController.as_view(), name="personnelles"),
    # path("personnelles/<int:id>",PersonnelleController.as_view(),name="personnelles-detail")
    path("contact-urgents", ContactUrgentController.as_view(), name="contact-urgents"),
    path("contact-urgents/<int:id>/", ContactUrgentController.as_view(), name="contact-urgent-detail"),
    path("fonctions", FonctionController.as_view(), name="fonctions"),
    path("fonctions/<int:id>/", FonctionController.as_view(), name="fonction-detail"),
    path("banques", BanqueController.as_view(), name="banques"),
    path("banques/<int:id>/", BanqueController.as_view(), name="banque-detail"),
    path("agences", AgenceController.as_view(), name="agences"),
    path("agences/<int:id>/", AgenceController.as_view(), name="agence-detail"),
    path("coordonnees-bancaires", CoordonneesBancaireController.as_view(), name="coordonnees-bancaires"),
    path("coordonnees-bancaires/<int:id>/", CoordonneesBancaireController.as_view(), name="coordonnee-bancaire-detail"),
    path("photos", PhotosController.as_view(), name="photos"),
    path("photos/<int:id>/", PhotosController.as_view(), name="photo-detail"),
    path("fullpersonnelles",PersonnelFullController.as_view(),name='fullpersonnelles'),
    path("familles",FamilleController.as_view(),name="familles"),
    path("familles/<int:id>/",FamilleController.as_view,name="famille-detail"),
    path('api/fullpersonnelles/<int:id>/', PersonnelFullController.as_view(), name='full-personnel-detail'),
    path('experiences', ExperienceController.as_view(), name='experience'),
    path('experiences/<int:id>/', ExperienceController.as_view(), name='experience-detail'),
    path('diplomes', DiplomeController.as_view(), name='diplome'),
    path('diplomes/<int:id>/', DiplomeController.as_view(), name='diplome-detail'),
    path('formations', FormationController.as_view(), name='formation'),
    path('formations/<int:id>/', FormationController.as_view(), name='formation-detail'),
    path('historiques-postes', HistoriqueDuPosteController.as_view(), name='historique'),
    path('historiques-postes/<int:id>/', HistoriqueDuPosteController.as_view(), name='historique-detail'),
    path('enfants', EnfantController.as_view(), name='enfant'),
    path('enfants/<int:id>/', EnfantController.as_view(), name='enfant-detail'),
    path('contrats',ContratController.as_view(),name='contrat'),
    path('contrats/<int:id>/', EnfantController.as_view(), name='enfant-detail'),
    path('typecontrats',TypeContratController.as_view(),name='type_contrat'),
    path('typecontrats/<int:id>/', EnfantController.as_view(), name='enfant-detail'),
    path('modefinancement',ModeFinancementController.as_view(),name='ModeFinancement'),
    path('modefinancement/<int:id>/', ModeFinancementController.as_view(), name='ModeFinancement'),
    path('logins', LoginController.as_view(), name='logins'),
    path('logins/<int:id>/', LoginController.as_view(), name='login-detail'),
    path('roles', RoleController.as_view(), name='roles'),
    path('roles/<int:id>/', RoleController.as_view(), name='role-detail'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
