from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from api.controllers import *
from api.controllers.conge.validationController import ValidationCongeController
from api.controllers.personnelles.fonction.superieurController import SuperieurController
from api.controllers.conge.soldeCongeController import SoldeCongeRHController
from api.controllers.conge.congePlanifieController import CongePlanifieController, CongePlanifieDetailController
from .controllers import ConfigPlanningController
urlpatterns = [
    path('login', LoginController.as_view(), name='login'),
    path('personnelle', PersonnelleController.as_view(), name='personnelle'),
    path('etat-civils', EtatCivilController.as_view(), name='etat-civils'),
    path('etat-civils/<int:id>/', EtatCivilController.as_view(), name="etatcivil-detail"),
    path('propos', ProposController.as_view(), name='propos'),
    path("propos/<int:id>/", ProposController.as_view(), name="propos-detail"),
    path("sexes", SexeController.as_view(), name="sexes"),
    path("sexes/<int:id>/", SexeController.as_view(), name="sexe-detail"),
    path("services", ServiceController.as_view(), name="services"),
    path("services/<int:id>/", ServiceController.as_view(), name="service-detail"),
    path("postes", PosteController.as_view(), name="postes"),
    path("postes/<int:id>/", PosteController.as_view(), name="poste-detail"),
    path("relations", RelationController.as_view(), name="relations"),
    path("relations/<int:id>/", RelationController.as_view(), name="relation-detail"),
    path("cins", CinsController.as_view(), name="cins"),
    path("cins/<int:id>/", CinsController.as_view(), name="cins-detail"),
    path("personnelles", PersonnelleController.as_view(), name="personnelles"),
    path("personnelles/<int:id>/",PersonnelleController.as_view(),name="personnelles-detail"),
    path("contact-urgents", ContactUrgentController.as_view(), name="contact-urgents"),
    path("contact-urgents/<int:id>/", ContactUrgentController.as_view(), name="contact-urgent-detail"),
    path("fonctions", FonctionController.as_view(), name="fonctions"),
    path("fonctions/<int:id>/", FonctionController.as_view(), name="fonction-detail"),
    path("banques", BanqueController.as_view(), name="banques"),
    path("banques/<int:id>/", BanqueController.as_view(), name="banque-detail"),
    path("agences", AgenceController.as_view(), name="agences"),
    path("agences/<int:id>/", AgenceController.as_view(), name="agence-detail"),
    path("coordonnees-bancaires", CoordonneesBancaireController.as_view(), name="coordonnees-bancaires"),
    path("coordonnees-bancaires/<int:id>/", CoordonneesBancaireController.as_view(), name="coordonnee-bancaire-detail"),
    path("photos", PhotosController.as_view(), name="photos"),
    path("photos/<int:id>/", PhotosController.as_view(), name="photo-detail"),
    path("fullpersonnelles",PersonnelFullController.as_view(),name='fullpersonnelles'),
    path("familles",FamilleController.as_view(),name="familles"),
    path("familles/<int:id>/",FamilleController.as_view(),name="famille-detail"),
    # path('fullpersonnelles/<int:id>/', PersonnelFullController.as_view(), name='full-personnel-detail'),
    path('fullpersonnelles/<int:pk>/', PersonnelFullController.as_view()),
    path('experiences', ExperienceController.as_view(), name='experience'),
    path('experiences/<int:id>/', ExperienceController.as_view(), name='experience-detail'),
    path('diplomes', DiplomeController.as_view(), name='diplome'),
    path('diplomes/<int:id>/', DiplomeController.as_view(), name='diplome-detail'),
    path('formations', FormationController.as_view(), name='formation'),
    path('formations/<int:id>/', FormationController.as_view(), name='formation-detail'),
    path('enfants', EnfantController.as_view(), name='enfant'),
    path('enfants/<int:id>/', EnfantController.as_view(), name='enfant-detail'),
    path('contrats',ContratController.as_view(),name='contrat'),
    path('contrats/<int:id>/', ContratController.as_view(), name='enfant-detail'),
    path('typecontrats',TypeContratController.as_view(),name='type_contrat'),
    path('typecontrats/<int:id>/', ContratController.as_view(), name='enfant-detail'),
    path('modefinancement',ModeFinancementController.as_view(),name='ModeFinancement'),
    path('modefinancement/<int:id>/',ModeFinancementController.as_view(), name='ModeFinancement'),
    path('logins', LoginController.as_view(), name='logins'),
    path('logins/<int:id>/', LoginController.as_view(), name='login-detail'),
    path('roles', RoleController.as_view(), name='roles'),
    path('roles/<int:id>/', RoleController.as_view(), name='role-detail'),
    path('permission', PermissionController.as_view(), name='permission'),
    path('permission/<int:id>/', PermissionController.as_view(), name='permission-detail'),
    path('admin', LoginadminController.as_view(), name='admin'),
    path('admin/<int:id>/', LoginadminController.as_view(), name='admin-detail'),
    path('conge',CongeController.as_view(), name='conge'),
    path('conge/<int:id>/',CongeController.as_view(),name='conge-detail'),
    path('statut',StatutController.as_view(),name='statut'),
    path('statut/<int:id>/',StatutController.as_view(),name='statut-detail'),
    path('solde_conge',SoldeCongeController.as_view(),name='solde-conge'),
    path('solde_conge/<int:id>/',SoldeCongeController.as_view(),name='solde_conge-detail'),
    path('type_conge',TypeCongeController.as_view(), name='type_conge'),
    path('type_conge/<int:id>/',TypeCongeController.as_view(),name='type_conge-detail'),
    path('passation_service', PassationServiceController.as_view(), name='passation_service'),
    path('passation_service/<int:id>/', PassationServiceController.as_view(), name='passation_service-detail'),
    path('user',UserManagementController.as_view(), name='user'),
    path('user/<int:id>/',UserManagementController.as_view(),name='usermanage'),
    path('conge/<int:conge_id>/valider/', ValidationCongeController.as_view()),
    path('superieurs', SuperieurController.as_view()),
    path('superieurs/<int:fonction_id>/', SuperieurController.as_view()),
    path('rh/soldes/', SoldeCongeRHController.as_view()),
    path('rh/soldes/<int:solde_id>/',SoldeCongeRHController.as_view()),
    path('personnelles/<int:id>/toggle-status/', PersonnelleController.as_view(), name='toggle-status'),
    path('conges-planifies/<int:personnel_id>/', CongePlanifieController.as_view(), name='conges-planifies-personnel'),
    path('conges-planifies/detail/<int:id>/', CongePlanifieDetailController.as_view(), name='conge-planifie-detail'),
    path('conges-planifies/', ConfigPlanningController.as_view(), name='config-planification'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
